import Head from "next/head";
import { getSession } from "next-auth/react";
import { NextPageContext } from "next";
import Navbar from "@/components/Navbar";
import Billboard from "@/components/Billboard";
import MovieList from "@/components/MovieList";
import useMovieList from "@/hooks/useMovieList";
import useRandomDrama from "@/hooks/useRandomDrama";
import useRandomThriller from "@/hooks/useRandomThriller";
import useRandomCrime from "@/hooks/useRandomCrime";
import useRandomAdventure from "@/hooks/useRandomAdventure";
import useFavorites from "@/hooks/useFavorites";

export default function Home() {
  const { data: drama = [] } = useRandomDrama()
  const { data: thriller = [] } = useRandomThriller()
  const { data: crime = [] } = useRandomCrime()
  const { data: adventure = [] } = useRandomAdventure()
  const { data: favorites = [] } = useFavorites()

  return (
    <>
      <Head>
        <title>Boronilov Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/Reactions-New-Netflix-Original-Logo-Animation-2019.webp"
        />
      </Head>

      <section>
        <Navbar />
        <Billboard />
      </section>

      <main>
        <div className="pb-40">
          <MovieList title="Drama" data={drama} />
          <MovieList title="Thriller" data={thriller} />
          <MovieList title="Crime" data={crime} />
          <MovieList title="Adventure" data={adventure} />
          <MovieList title="My list" data={favorites} />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/auth",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
