import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Boronilov Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/netflix-logo-icon-on-white-background-free-vector.webp" />
      </Head>
      <h1 className="text-2xl text-green-500">Hello Netflix</h1>
    </>
  );
}
