import Head from "next/head";
import { getSession } from "next-auth/react";
import { NextPageContext } from "next";
import Navbar from "@/components/Navbar";
import MovieList from "@/components/MovieList";
import dynamic from 'next/dynamic'
import useInfoModal from "@/hooks/useInfoModal";
import useSeries from "@/hooks/useSeries";

export default function Series() {
  const { data: series = [] } = useSeries()

  const {isOpen, closeModal} = useInfoModal()

  const DynamicModal = dynamic(() => import('@/components/InfoModal'), {
    ssr: false,
  })

  return (
    <>
      <Head>
        <title>Boronilov Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/Reactions-New-Netflix-Original-Logo-Animation-2019.webp"
        />
      </Head>

      <section>
        <DynamicModal visible={isOpen} onClose={closeModal}/>
        <Navbar />
      </section>

      <main>
        <div className="pt-20">
          <MovieList title="Series" data={series} />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/auth",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
